set nocompatible	" Use vim defaults
set backspace=indent,eol,start  " allow backspacing over autoindent, line breaks, start of the insert
set ruler       " display current row and column position
set viminfo='20,\"50    " read/write a .viminfo file, don't store more than 50 lines of registers
set history=50  " store 50 lines of command line history
